### ISSUE TITLE
Faster startup time

### ISSUE THREAD

**Issue by bryce-hoehn** [17hoehbr/apple-music-electron#11]
So far I've mostly been using the AUR package which seems to launch smoothly, but the AppImage version seems to just open to a black screen for up to about 5 seconds or so. 

One option proposed by @thvozdovic was to add a loading window similar to Discord's, though I would prefer to further optimize the app so it just launches fast enough that this isn't necessary.

I've started following some of the basic tips on this page: https://www.electronjs.org/docs/tutorial/performance. My most recent commit for example moved some of the require() lines down to when they were needed rather than all at once at the beginning of the code. This seems to help a lot but the AppImage is still a bit slower than I'd like.

In the meantime users might want to avoid the AppImage release if possible, though they will not get automatic updates if they switch to the deb package until I make a PPA for it.

If the AppImage is still too slow after further optimizing then I would be willing to include a loading window, but I would then also like to see it behave like Discord's by giving update status messages.

**Comment by 17hoehbr** [comment]
Maybe I'll just kill off the AppImage format if this issue persists in favor of Snap or Flatpak if it fixes the startup time.

**Comment by bryce-hoehn** [comment]
daa52cf and 8ee67df should both improve startup times without the need for a loading window

**Comment by bryce-hoehn** [comment]
keeping open as an on going optimization issue. it would be extremely helpful if anyone could comment their load times and thoughts on it.

**Comment by thvozdovic** [comment]
Maybe add some asset cache that would save all resources into a cache and then when the app is launched again it would use that file?

**Comment by bryce-hoehn** [comment]
cbd6a02 adds code caching and asset caching. Try it out and let me know how it works. Assuming startup times are improved and there's no major issue I'll close this issue.

**Comment by bryce-hoehn** [comment]
no idea if I used express-asset-file-cache-middleware correctly but it doesn't seem to have broken anything and its launching faster lol

**Comment by thvozdovic** [comment]
I wanted to implement the same modules but didn't have the time to do so. Looks fine and it loads faster

**Comment by bryce-hoehn** [comment]
[v1.2.3](https://github.com/17hoehbr/apple-music-electron/tree/v1.2.3) closes this issue
