### ISSUE TITLE
Cannot add song to a playlist

### ISSUE THREAD

**Issue by thvozdovic** [17hoehbr/apple-music-electron#13]
I'm unable to add song to a playlist
![image](https://user-images.githubusercontent.com/25270138/99887359-f2086700-2c43-11eb-8e6d-9444dd194f19.png)
The second menu will not show.
On the website the button itself is not even visible. This is most likely an issue with Apple Music but I just want to make sure it's not only on my side.

**Comment by bryce-hoehn** [comment]
I'm having the same issue. Apple Music's web client has never had the option to add songs to playlists afaik, but the Add to Playlist button is new. Hopefully this means they're working on it ¯\_(ツ)_/¯
