### ISSUE TITLE
Pressing the ALT key, causes the Settings menu to appear 

### ISSUE THREAD

**Issue by CHJ85** [17hoehbr/apple-music-electron#16]
Hi there. Could you please fix this very annoying thing. When I press the alt key

**Comment by bryce-hoehn** [comment]
Pressing Alt is supposed to show the settings menu

**Comment by CHJ85** [comment]
@17hoehbr I know. But isn't there a way to disable that feature. Sorry. I should probably explain what the actual problem is..
You see, the alt key conflicts with other functions that also uses the alt key. For instance, whenever I press alt+right arrow to skip to the next song, or alt+left arrow to restart the song, or alt+left arrow twice to go back to the previous song and so on, that stupid settings menu pops up. It also conflicts with zooming. Because alt+mousewheel zooms in and out.
So anyway. That settings menu annoys the crap out of me. Is there a way to get rid of it once and for all?
