### ISSUE TITLE
Deduplication of efforts

### ISSUE THREAD

**Issue by fridtjof** [17hoehbr/apple-music-electron#24]
While looking for an AUR package for this electron client: https://github.com/cryptofyre/Apple-Music-Electron, I stumbled upon this repository.

Now, it seems like both of you seem to have the same goal essentially. Maybe it makes sense to collaborate? Or are there major differences that I did not spot at first glance?

(I crossposted to the other repository for visibility, as I could not mention its owner from here)

**Comment by bryce-hoehn** [comment]
[https://github.com/cryptofyre/Apple-Music-Electron/issues/98](url)
