### ISSUE TITLE
How to manually enable dark theme

### ISSUE THREAD

**Issue by ghost** [17hoehbr/apple-music-electron#25]
Currently running the latest rpm package of the app on Fedora 34. Is there any way to manually enable dark mode ?

**Comment by bryce-hoehn** [comment]
Yes! I suppose I forgot to document it but if you press Alt a settings toolbar will appear at the top of the application. Click on the settings drop down and there should be a button to toggle dark mode manually. After doing so I would recommend restarting the app as it can cause some weird CSS issues but after that it should work and persist through restarts.
