### ISSUE TITLE
Minor interface fix --> change scrollbar colors in dark mode

### ISSUE THREAD

**Issue by sollymay** [17hoehbr/apple-music-electron#3]
Hey @17hoehbr! I am using your app to stream Apple Music when using linux and it's been really useful!

One minor interface fix I think you can push is to make sure the scrollbars match the color pattern when in dark mode. 

![Screenshot from 2020-10-23 22-57-46](https://user-images.githubusercontent.com/6496698/97066405-3b9d5d80-1583-11eb-84ad-d1f43d3665a0.png)

I think it's relativily easy to do since the scrollbars seem to be part of the wrapper itself?

https://discuss.atom.io/t/customize-scrollbar-in-webview/32661/4

Thanks!

**Comment by bryce-hoehn** [comment]
Hey I'm glad you're enjoying this app! I haven't touched it in a few months but I just fixed this along with a few other bugs. I wasn't sure how to make the scroll bar adapt to the theme so instead I just made a custom scroll bar that should look pretty good in both light and dark mode. Download the latest release here: [https://github.com/17hoehbr/Apple-Music-Wrapper/releases/tag/v1.1.0](url) or compile from source by following the instructions in the README. Hoping to add this to some package managers soon so you don't have to keep manually updating.
