### ISSUE TITLE
Dark mode on PopOS

### ISSUE THREAD

**Issue by thvozdovic** [17hoehbr/apple-music-electron#7]
Hello,
the wrapper is working great except the dark mode, the website is in light mode even though I have dark mode enabled in the OS Settings.

**Comment by thvozdovic** [comment]
Hey, I managed to fix it by adding this line:
```js
  if(nativeTheme.shouldUseDarkColors) nativeTheme.themeSource = 'dark';
```
You can check the pull request I made #8

**Comment by bryce-hoehn** [comment]
Thanks! I was wondering why dark mode wasn't working for me lol. Also thanks for getting rid of the Open in iTunes button I didn't realize you could do that.
