### ISSUE TITLE
Custom settings

### ISSUE THREAD

**Issue by thvozdovic** [17hoehbr/apple-music-electron#9]
Hello,
I was thinking if we could add a custom settings into the taskbar, the one I want is "Enable Beta" option which if toggled would use [beta.music.apple.com](https://beta.music.apple.com) instead of [music.apple.com](https://music.apple.com).
If yes, I can make a pull request since I already made it

**Comment by bryce-hoehn** [comment]
Sounds good, I'm not really sure what's different in the beta but I just tried it and it seems to run much smoother. If we're adding custom settings I think a dark mode toggle would be another good option.

**Comment by bryce-hoehn** [comment]
I might even just make the beta the default for now at least because it fixes an annoying bug where the page reloads a few seconds after the app opens.

**Comment by thvozdovic** [comment]
Okay, I will add dark mode toggle as well.

**Comment by thvozdovic** [comment]
#10

**Comment by thvozdovic** [comment]
Also, what if we made a small loading window untill the ui has fully loaded? That way once it opens up you will be able to use it right away. Some custom js with rpc should work

**Comment by thvozdovic** [comment]
![image](https://user-images.githubusercontent.com/25270138/99732461-d3796300-2abf-11eb-9a6a-6fba1f9c443d.png)
Something like this, it would then close that window and open the app, like Discord does.
*It animates, that's why it has low opacity, I don't know how to record gif on popos*

**Comment by bryce-hoehn** [comment]
I'm liking the new settings menu but I'd prefer to avoid having a separate loading window. On my end with the AUR package it only takes a second or two to launch anyway. If you're having performance issues let me know which package you're using and I'll try to optimize load times over implementing a loading window.
